## <u> Use only those concepts which have been taught till now </u>

# <b> Problem 1: Import Pandas and Numpy in the notebook </b>

In [1]:
# Import statements
!pip install pandas
!pip install numpy
import pandas as pd
import numpy as np

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2022.7.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.22.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (1.22.4)

# <b> Problem 2 : Load the automobile_data.csv kept in the shared folder

In [ ]:
# Mount your drive and read the csv file. Make sure you are using the correct file path
df = pd.read_csv('./automobile_data.csv')
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.4,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

# <b> Problem 3 : Do a basic inspection and print the first and last 15 rows of your dataframe

In [ ]:
# Your code here
df.head(15) # first 15 rows

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450
5,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,17710
7,1,?,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.4,8.3,140,5500,17,20,23875
9,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.4,7.0,160,5500,16,22,?
10,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.5,2.8,8.8,101,5800,23,29,16430
11,0,192,bmw,gas,std,four,sedan,rwd,front,101.2,...,108,mpfi,3.5,2.8,8.8,101,5800,23,29,16925
12,0,188,bmw,gas,std,two,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,20970
13,0,188,bmw,gas,std,four,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,21105
14,1,?,bmw,gas,std,four,sedan,rwd,front,103.5,...,164,mpfi,3.31,3.19,9.0,121,4250,20,25,24565

In [ ]:
df.tail(15) #last 15 rows

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
190,3,256,volkswagen,gas,std,two,hatchback,fwd,front,94.5,...,109,mpfi,3.19,3.4,8.5,90,5500,24,29,9980
191,0,?,volkswagen,gas,std,four,sedan,fwd,front,100.4,...,136,mpfi,3.19,3.4,8.5,110,5500,19,24,13295
192,0,?,volkswagen,diesel,turbo,four,sedan,fwd,front,100.4,...,97,idi,3.01,3.4,23.0,68,4500,33,38,13845
193,0,?,volkswagen,gas,std,four,wagon,fwd,front,100.4,...,109,mpfi,3.19,3.4,9.0,88,5500,25,31,12290
194,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,12940
195,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,13415
196,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,24,28,15985
197,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,24,28,16515
198,-2,103,volvo,gas,turbo,four,sedan,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162,5100,17,22,18420
199,-1,74,volvo,gas,turbo,four,wagon,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162,5100,17,22,18950
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.4,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

# <b>Problem 4 : You need to clean the data a little bit now. Replace all column values with the values <code>?</code> and <code>n.a</code> with <code>NaN</code>

In [ ]:
# Your code here
df.replace('?', float('nan'), inplace=True)
df.replace('n.a', float('nan'), inplace=True)
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.4,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

# <b>Problem 5 : Print the company name which manufactured the most expensive car. Also print the price of the most expensive car

In [ ]:
# Your code here
#the company which manifacture most expensive are is:
df['price'] = pd.to_numeric(df['price'], errors='coerce')
df.dropna(subset=['price'], inplace=True)
most_expensive_company = df.loc[df['price'].idxmax(), 'make']
most_expensive_company

'mercedes-benz'

# <b>Problem 6 : Calculate maximum horsepowers for each company. </b>

In [ ]:
# Your code here
df.dropna(subset=['horsepower'], inplace=True)
selected_columns = df[['make', 'horsepower']]
#maximum horse powers
selected_columns

            make horsepower
0    alfa-romero        111
1    alfa-romero        111
2    alfa-romero        154
3           audi        102
4           audi        115
..           ...        ...
200        volvo        114
201        volvo        160
202        volvo        134
203        volvo        106
204        volvo        114

[199 rows x 2 columns]

# <b> Problem 7 : Print the total number of cars manufactured by each company

In [ ]:
# Your code here

# Group the DataFrame by the 'make' column and count the number of occurrences
car_count_per_company = df['make'].value_counts().reset_index()

# Rename the columns for better representation
car_count_per_company.columns = ['Company Name', 'Number of Cars']
car_count_per_company

     Company Name  Number of Cars
0          toyota              32
1          nissan              18
2           mazda              17
3           honda              13
4      mitsubishi              13
5      volkswagen              12
6          subaru              12
7           volvo              11
8          peugot              11
9           dodge               9
10            bmw               8
11  mercedes-benz               8
12       plymouth               7
13           saab               6
14           audi               6
15        porsche               4
16    alfa-romero               3
17         jaguar               3
18      chevrolet               3
19          isuzu               2
20        mercury               1

# <b> Problem 8 : Create a new column for the updated price. This updated price will be calculated on top of the given price - if the engine is in front, price will be same else if the engine is in rear, price will be doubled </b>

In [ ]:
# Your code here. Use apply and lambda
import pandas as pd

def update_price_based_on_engine_location(df):

    df['updated_price'] = df.apply(lambda row: row['price'] if row['engine-location'] == 'front' else row['price'] * 2, axis=1)


update_price_based_on_engine_location(df)

    # Filter only the 'price' and 'updated_price' columns for not front engine --> I am checking here
filtered_data = df[df['engine-location'] == 'front'][['price', 'updated_price']]
filtered_data

       price  updated_price
0    13495.0        13495.0
1    16500.0        16500.0
2    16500.0        16500.0
3    13950.0        13950.0
4    17450.0        17450.0
..       ...            ...
200  16845.0        16845.0
201  19045.0        19045.0
202  21485.0        21485.0
203  22470.0        22470.0
204  22625.0        22625.0

[196 rows x 2 columns]

# <b>Problem 9 : Sort the dataframe by car and price columns

In [ ]:
# Your code here
sorted_val=df[['make', 'price']]
sorted_val

            make    price
0    alfa-romero  13495.0
1    alfa-romero  16500.0
2    alfa-romero  16500.0
3           audi  13950.0
4           audi  17450.0
..           ...      ...
200        volvo  16845.0
201        volvo  19045.0
202        volvo  21485.0
203        volvo  22470.0
204        volvo  22625.0

[199 rows x 2 columns]

# <b> Problem 10 : Create a new column which stores the number of doors in a car as integers.

In [ ]:
# Your code here. Use apply
def convert_string_numbers_to_int(df):

    number_mapping = {
        'one':1,
        'two': 2,
        'three': 3,
        'four': 4,
        'five': 5,
        # Add more mappings as needed
    }


    df['num-of-doors_integers'] = df['num-of-doors'].map(number_mapping)

convert_string_numbers_to_int(df)
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,updated_price,num-of-doors_integers
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,3.47,2.68,9.0,111,5000,21,27,13495.0,13495.0,2.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,3.47,2.68,9.0,111,5000,21,27,16500.0,16500.0,2.0
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,2.68,3.47,9.0,154,5000,19,26,16500.0,16500.0,2.0
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,3.19,3.4,10.0,102,5500,24,30,13950.0,13950.0,4.0
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,3.19,3.4,8.0,115,5500,18,22,17450.0,17450.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,3.78,3.15,9.5,114,5400,23,28,16845.0,16845.0,4.0
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,3.78,3.15,8.7,160,5300,19,25,19045.0,19045.0,4.0
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,3.58,2.87,8.8,134,5500,18,23,21485.0,21485.0,4.0
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,3.01,3.4,23.0,106,4800,26,27,22470.0,22470.0,4.0
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,3.78,3.15,9.5,114,5400,19,25,22625.0,22625.0,4.0

# <b>Problem 11 : Concatenate the two data frames given below firstly row wise and secondly column wise.</b>

<code>GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]}</code>

<code>japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}</code>

In [ ]:
# Your code here
GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]}

japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}

In [ ]:
GermanCarsData_frame=pd.DataFrame(GermanCars)
JapaneseCarsData_frame=pd.DataFrame(japaneseCars)

In [ ]:
row_wise = pd.concat([GermanCarsData_frame, JapaneseCarsData_frame], axis=0, ignore_index=True)


column_wise = pd.concat([GermanCarsData_frame, JapaneseCarsData_frame], axis=1)

print("Concatenated Row-wise:")
row_wise

Concatenated Row-wise:

       Company   Price
0         Ford   23845
1     Mercedes  171995
2          BMV  135925
3         Audi   71400
4       Toyota   29995
5        Honda   23600
6       Nissan   61500
7  Mitsubishi    58900

In [ ]:
column_wise

    Company   Price      Company  Price
0      Ford   23845       Toyota  29995
1  Mercedes  171995        Honda  23600
2       BMV  135925       Nissan  61500
3      Audi   71400  Mitsubishi   58900