In [ ]:
# Problem 1
# In a cricket tournament, based on the outcome of a particular match a team gets following points:

# wins gets 7 points
# draws gets 2 points
# losses gets 0 points
# Team Aravali plays 8 matches in this tournament. It wins 4 matches, loses 3 matches and draws 1. What is the total number of points gained by the Team austria?


# a) The outcome variables are defined below?
# b) Calculate the total points gained by Team Austria and print.

In [ ]:
wins=7

draw=2

Losses= 0

print( 4*wins + 3*Losses + draw )

30

In [ ]:
#Problem 2
#Root of a function  f(x)  is defined as the value  x  where  f(x)=0
#Consider a quadratic function  f(x)=x2+3x−4
#Find the value of the function  f(x)  at points  x=7,x=−1,x=1 .
#  a)Calculate the value of the function f(x) at x = 2.
#  b) Calculate the value of the function f(x) at x = 1

In [10]:
def f(x):
    return (x**2)+(3*x)-4

print(f(7),f(-1),f(1),f(2),f(1))

66 -6 0 6 0

In [ ]:
# Problem 3
# A list contains the average daily temperature(in degree Celsius) of a city over a particular week. Write a Python code to swap the highest and the lowest temperatures

# a) A list containing average daily temperature over a week
# temperatures = [34, 40, 29, 33, 42, 37, 39 ]

# b) The expected output



# c)Store the highest temperature


# d) Index of the element with the highest temperature
# max_temp_index =


# e) Store the lowest temperature
# min_temp =

# f) Index of the element with the lowest temperature
# min_temp_index =

In [ ]:
# b) The expected output

temperatures = [34, 40, 29, 33, 42, 37, 39]
highest = 0
lowest = 0

for i in range(0,7):
    if temperatures[i] >= temperatures[highest]:
        highest = i
    if temperatures[i] <= temperatures[lowest]:
        lowest = i


print("lowest:", temperatures[lowest], "highest:", temperatures[highest])

# Swap the values of lowest and highest without a separate function
lowest, highest = highest, lowest

print("After swapping - lowest:", temperatures[lowest],"-->index:",lowest, "highest:", temperatures[highest],'-->index:',highest)

lowest: 29 highest: 42
After swapping - lowest: 42 -->index: 4 highest: 29 -->index: 2

In [ ]:

# Problem 7 - numpy
# Construct a 2-D  10∗10  matrix with the following constraints:
# The element at  [0,0]  should be 1
# The element at  [0,9]  should be 100
# The element at  [9,0]  should be 50
# The interval between elements in rows should be constant
# The interval between elements in columns should be constant

In [2]:
!pip install numpy
!pip install pandas
import numpy as np
import pandas as pd

Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (1.22.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2022.7.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.22.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [8]:
start_value = 1
end_value_row0 = 100
end_value_row9 = 50
matrix_size = 10

matrix = np.zeros((matrix_size, matrix_size), dtype=int)

interval_row = (end_value_row0 - start_value) / (matrix_size - 1)
interval_col = (end_value_row9 - start_value) / (matrix_size - 1)

matrix[0, 0] = start_value
for col in range(1, matrix_size):
    matrix[0, col] = matrix[0, col - 1] + interval_row

matrix[0, 9] = end_value_row0
for row in range(1, matrix_size):
    matrix[row, 9] = matrix[row - 1, 9] + interval_col

matrix[9, 0] = end_value_row9

print(matrix)

[[  1  12  23  34  45  56  67  78  89 100]
 [  0   0   0   0   0   0   0   0   0 105]
 [  0   0   0   0   0   0   0   0   0 110]
 [  0   0   0   0   0   0   0   0   0 115]
 [  0   0   0   0   0   0   0   0   0 120]
 [  0   0   0   0   0   0   0   0   0 125]
 [  0   0   0   0   0   0   0   0   0 130]
 [  0   0   0   0   0   0   0   0   0 135]
 [  0   0   0   0   0   0   0   0   0 140]
 [ 50   0   0   0   0   0   0   0   0 145]]

In [5]:
#Problem 8  - numpy
#Construct a list of first 100 natural numbers.Create a two dimensional array with 10 rows and whose each row contains 10 columns and each number in this array is the square of the number from your constructed list.
#For example : [[1,4,9,...,100],[121,144,...],......,]

In [6]:
import numpy as np

first_100_natural_numbers = list(range(1, 101))

matrix = np.array(first_100_natural_numbers).reshape(10, 10)

squared_matrix = matrix ** 2

print(squared_matrix)

[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]